services:
  - type: web
    name: beautiful-soup-flask
    env: python
    rootDir: .
    buildCommand: pip install -r /opt/render/project/src/requirements.txt
    startCommand: gunicorn --chdir /opt/render/project/src adapters.flask_app:app